apiVersion: v1
kind: ConfigMap
metadata:
  name: travelmind-config
  namespace: travelmind
data:
  NODE_ENV: "production"
  PORT: "3000"
  APP_NAME: "travelmind-api"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-service:5672"
  ELASTICSEARCH_URL: "http://elasticsearch-service:9200"
  LOGSTASH_HOST: "logstash-service"
  LOGSTASH_PORT: "5044"
