apiVersion: v1
kind: Service
metadata:
  name: travelmind-api-service
  namespace: travelmind
spec:
  selector:
    app: travelmind-api
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
